#!/bin/sh

if [ -f /bin/exa ]; then
    alias ls="exa"
else
    alias ls="ls --color=auto"
fi

alias ll="ls -lh"
alias la="ls -all"

if [ -f /bin/bat ]; then
    alias cat="bat"
fi

if [ -f /bin/zoxide ]; then
    alias z="zoxide"
    alias zz="z -"
    alias cd="zoxide"
fi

if [ -f /bin/nvim ]; then
    alias vim="nvim"
fi

if [ -f /bin/lazygit ]; then
    alias lg="lazygit"
fi

if grep -q -i microsoft /proc/version; then
    alias toclip="clip.exe"
else
    alias toclip="xclip -selection clipboard"
fi

if [ -f /bin/fdfind ]; then
    alias fd="fdfind"
fi

if [ -f /bin/fd ]; then
    alias find="fd"
fi

function ff() {
    fd -t f -L -H -E .git $*
}

function getpath() {
    fd -t f | fzf | sed 's/^\.\///' | tr -d '\n' | toclip
}

function getabspath() {
    fd -t f -a | fzf | sed 's/^\.\///' | tr -d '\n' | toclip
}

function fcd() {
    cd "$(fd -d 5 -t d -L -H -E .git | fzf)"
}

function open() {
    nvim "$(fd -d 5 -t f -L -H -E .git | fzf)"
}

function rf() {
    rm -f "$(fd -d 5 -t f -L -H | fzf -m)"
}

function rd() {
    rm -rf "$(fd -d 5 -t d -L -H | fzf -m)"
}

export FZF_DEFAULT_COMMAND='fd -t f -L -H -E .git'

alias pull="git pull"
alias push="git push"
alias stage="git stage"
alias checkout="git checkout"
alias reset="git reset"
alias commit="git commit"
alias submodule="git submodule"
