#! /bin/sh

#BSPWM Config
bspc config border_width        1
bspc config top_padding         30
bspc config right_padding       5
bspc config left_padding        5
bspc config bottom_padding      5
bspc config window_gap          2
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

# Variable Defines
color0=#3B4252
color4=#D8DEE9
color10=#5e81ac

bspc config focused_border_color "$color10"
bspc config normal_border_color  "$color0"
bspc config active_border_color  "$color0"
bspc config presel_feedback_color "$color4"
bspc config split_ratio          0.60
bspc config borderless_monocle   true  
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config merge_overlapping_monitors true

#Application Rules
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a variety state=floating
bspc rule -a Chromium desktop='^2'

# Start additional programs
~/.config/bspwm/scripts/multi_monitor_detection.sh

#Monitor Config
for m in $(xrandr --query | grep " connected " | cut -d" " -f1); do
  bspc monitor $m -d 1 2 3 4 5 6 7 8 9 10
done

feh --bg-fill /home/dennis/Wallpaper/dark_mountain_1.jpg &
bash ~/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -b --config ~/.config/picom/picom.conf &

# Fix cursor issue
xsetroot -cursor_name left_ptr
