local Color, colors, Group, groups, styles = require("colorbuddy").setup()


Color.new('nord0', "#2E3440")
Color.new('nord1',"#3B4252")
Color.new('nord2', "#434C5E")
Color.new('nord3', "#4C566A")
Color.new('nord3_light', "#616E88")
Color.new('nord4', "#D8DEE9")
Color.new('nord5', "#E5E9F0")
Color.new('nord6', "#ECEFF4")
Color.new('nord7', "#8FBCBB")
Color.new('nord8', "#88C0D0")
Color.new('nord9', "#81A1C1")
Color.new('nord10', "#5E81AC")
Color.new('nord11', "#BF616A")
Color.new('nord12', "#D08770")
Color.new('nord13', "#EBCB8B")
Color.new('nord14', "#A3BE8C")
Color.new('nord15', "#B48EAD")



Color.new('background', '#2E3440')
Color.new('bg', '#2E3440')
Color.new('foreground', '#ECEFF4')
Color.new('fg', '#ECEFF4')
Color.new('white', '#ECEFF4')
Color.new('red', '#BF616A')
Color.new('green', '#A3BE8C')
Color.new('yellow',  "#EBCB8B")
Color.new('blue',  "#5E81AC")
Color.new('aqua', '#A3BE8C')
Color.new('cyan',  "#8FBCBB")
Color.new('purple', "#B48EAD")
Color.new('violet', "#B48EAD")
Color.new('orange', "#D08770" )

-- my highlight
Group.new('TabLineSel', colors.foreground, colors.nord3, styles.bold )
Group.new('TabLineSelSeparator', colors.blue, colors.nord3)
Group.new('TabLine', colors.nord2, colors.nord2)
Group.new('TabLineFill', colors.nord1, colors.nord1)
Group.new('TabLineSeparator', colors.nord2, colors.none)

Group.new('Conceal', colors.nord3_light, colors.none)
Group.new('VertSplit', colors.nord3, colors.none)

Group.new('Normal', colors.nord4, colors.nord0)
Group.new('Function', colors.nord8, colors.none, styles.none)
Group.new('Error', colors.nord11, colors.none, styles.bold)
Group.new('ErrorMsg', colors.nord5, colors.nord11, styles.bold)
Group.new('WarningMsg', colors.nord5, colors.nord12, styles.bold)
Group.new('Boolean', colors.nord9, colors.none, styles.none)
Group.new('Character', colors.nord14, colors.none, styles.none)
Group.new('Comment', colors.nord3_light, colors.none, styles.italic)
Group.new("Conditional", colors.nord9, colors.none, styles.italic)
Group.new("Constant", colors.nord4, colors.none, styles.italic)
Group.new("Define", colors.nord9, colors.none, styles.none)
Group.new("Delimiter", colors.nord6, colors.none, styles.none)
Group.new("Exception", colors.nord9, colors.none, styles.none)
Group.new("Float", colors.nord15, colors.none, styles.none)
Group.new("Function", colors.nord8, colors.none, styles.none)
Group.new("Identifier", colors.nord4, colors.none, styles.none)
Group.new("Include", colors.nord9, colors.none, styles.none)
Group.new("Keyword", colors.nord7, colors.none, styles.italic)
Group.new("Label", colors.nord9, colors.none, styles.none)
Group.new("Number", colors.nord15, colors.none, styles.none)
Group.new("Operator", colors.nord9, colors.none, styles.none)
Group.new("PreProc", colors.nord9, colors.none, styles.none)
Group.new("Repeat", colors.nord9, colors.none, styles.none)
Group.new("Special", colors.nord4, colors.none, styles.none)
Group.new("SpecialChar", colors.nord13, colors.none, styles.none)
Group.new("SpecialComment", colors.nord8, colors.none, styles.italic)
Group.new("Statement", colors.nord9, colors.none, styles.none)
Group.new("StorageClass", colors.nord9, colors.none, styles.none)
Group.new("String", colors.nord14, colors.none, styles.none)
Group.new("Structure", colors.nord9, colors.none, styles.none)
Group.new("Tag", colors.nord4, colors.none, styles.none)
Group.new("Title", colors.nord4, colors.none)
Group.new("Todo", colors.nord13, colors.none, styles.none)
Group.new("Type", colors.nord9, colors.none, styles.none)
Group.new("Typedef", colors.nord9, colors.none, styles.none)
Group.new("CursorColumn", colors.nord1, colors.none, styles.none)
Group.new("LineNr", colors.nord9, colors.none, styles.none)
Group.new("CursorLineNr", colors.nord5, colors.none, styles.none)
Group.new("Line", colors.nord12, colors.none, styles.bold)
Group.new("SignColumn", colors.none, colors.none, styles.none)
Group.new("StatusLine", colors.nord8, colors.nord3, styles.none)

Group.new("ColorColumn", colors.none, colors.nord1)
Group.new("Cursor", colors.nord0, colors.nord4)
Group.new("CursorLine", colors.none, colors.none)
Group.new("iCursor",colors.nord0, colors.nord4)
Group.new("EndOfBuffer",colors.none, colors.none)
Group.new("MatchParen",colors.nord8, colors.nord3)
Group.new("NonText",colors.none, colors.none)
Group.new("PMenu", colors.nord4, colors.nord2)
Group.new("PmenuSbar", colors.nord4, colors.nord2)
Group.new("PMenuSel", colors.nord6, colors.nord9)
Group.new("PmenuThumb", colors.nord8, colors.nord3)
Group.new("SpecialKey",colors.nord3, colors.nord3)
Group.new("SpellBad",colors.nord11, colors.nord0)
Group.new("SpellCap",colors.nord13, colors.nord0)
Group.new("SpellLocal",colors.nord5, colors.nord0)
Group.new("SpellRare",colors.nord6, colors.nord0)
Group.new("Visual",colors.nord4, colors.nord9)
Group.new("VisualNOS",colors.nord2, colors.nord1)
Group.new("Folded", colors.nord14, colors.none, styles.italic)

-- "+- Neovim Support -+
Group.new("healthError",colors.nord11, colors.nord1)
Group.new("healthSuccess",colors.nord14, colors.nord1)
Group.new("healthWarning",colors.nord13, colors.nord1)
Group.new("TermCursorNC",colors.nord1, colors.nord1)
Group.new("IncSearch",colors.nord6, colors.nord10, styles.underline)
Group.new("Search",colors.nord1, colors.nord8)

-- vim
Group.new('vimcommand', groups.Statement, colors.none)
Group.new('vimLet', groups.vimcommand , colors.none)
Group.new('vimFuncVar', groups.identifier, colors.none)
Group.new('vimCommentTitle', groups.PreProc, colors.none)
Group.new('vimIsCommand', colors.none, colors.none)
Group.new('vimFuncSID', groups.Special, colors.none)
Group.new('vimMapModKey', groups.vimFuncSID, colors.none)
Group.new('vimMapLhs', colors.none, colors.none)
Group.new('vimNotation', colors.nord7, colors.none)
Group.new('vimBracket', groups.Delimiter, colors.none)
Group.new('vimMap', groups.vimcommand, colors.none)
Group.new('nvimMap', groups.vimMap, colors.none)

-- startify
Group.new("StartifyFile",colors.nord6, colors.none)
Group.new("StartifyFooter",colors.none, colors.none)
Group.new("StartifyHeader",colors.nord8, colors.none)
Group.new("StartifyNumber",colors.nord7, colors.none)
Group.new("StartifyPath",colors.nord8, colors.none)
Group.new("StartifyBracket", groups.Delimiter, groups.Delimiter)
Group.new("StartifySlash", groups.Normal, groups.Normal)
Group.new("StartifySpecial", groups.Comment, groups.Comment)

-- gitgutter
Group.new("GitGutterAdd", colors.nord14, colors.none)
Group.new("GitGutterDelete", colors.nord11, colors.none)
Group.new("GitGutterChange", colors.nord13, colors.none)
Group.new("GitGutterChangeDelete", colors.nord11, colors.none)

-- built-in LSP
Group.new("LSPDiagnosticsDefaultWarning", colors.nord13, colors.none)
Group.new("LSPDiagnosticsDefaultError", colors.nord11, colors.none)
Group.new("LSPDiagnosticsDefaultInformation", colors.nord8, colors.none)
Group.new("LSPDiagnosticsDefaultHint", colors.nord10, colors.none)
Group.new("LSPDiagnosticsSignWarning", colors.nord13, colors.none)
Group.new("LSPDiagnosticsSignError", colors.nord11, colors.none)
Group.new("LSPDiagnosticsSignInformation", colors.nord8, colors.none)
Group.new("LSPDiagnosticsSignHint", colors.nord10, colors.none)
Group.new("LSPDiagnosticsFloatingWarning", colors.nord13, colors.none)
Group.new("LSPDiagnosticsFloatingError", colors.nord11, colors.none)
Group.new("LSPDiagnosticsFloatingInformation", colors.nord8, colors.none)
Group.new("LSPDiagnosticsFloatingHint", colors.nord10, colors.none)

Group.new("LSPReferenceText", colors.none, colors.none)
Group.new("LSPReferenceRead", colors.none, colors.none, styles.bold)
Group.new("LSPReferenceWrite", colors.nord9, colors.none, styles.bold)

-- TeleScope
Group.new("TeleScopeSelection", colors.nord4, colors.nord3, styles.bold)
Group.new("TeleScopeMatching", colors.nord13)
-- Markdown
Group.new("markdownError", colors.nord4, colors.none)

